travis:
  secure:
    BINSTAR_TOKEN: k1BDs2EEH205S09qWdKpHN5QOivunqN6z2BNVOl8UdwfykodJE+X/wNoNBYe1O46sMaibhrApXkY2F2SiVlNsXb+nhV6tm6/sOFdPOv2M6rG2y/SyUFuAs4Iq/IkwHYsCRpj1HMX6cElcMvsXX48N5p3JISAwbe565/Usy61mmN7mbqlzfAzkOWzYIhM0RuJyMaIOd5e8EXVySFwQvC9T/va1SLx2bV/3hoeOqhtpcAwobvZbplqFsobRRgyE2Qyw2I8qw0GAEhTUppngKs1350Pv68aGjZNjaaKwaeOl4Te3NYuYhsUzEuoo1Y8UWa3m2+WEEQANJlNqTAODfmEY4zTw8Xn0729XMNljBh1CwtkiukjszvVZPQxuPYFu6w+nDtMWQ2iqIVaJNfGNjst0oQ4Vm6FjCFpwGNcv+Cu3c58VzWhue17N6/Mnov7C37t63zfMsWqDpn2MoNebembcdWHSSvbKf/825gdOk36x5OQwjuM+sEAekSOwAiwt8Ga9ZDKfLex5C8Tal9Y3bZs6n0pIkFaZblQC16/jqnj/IyZtyMPufdoJT2vpo9xxwD//ZAZKpkeD13Q2n7jkb2ow7plocSWpKBtPFo8FcDXS65Snqk69OMGm8miPSMPUHdGxPHKUSrldJUcsAu9GZcuqx/oFmPceY2oCuwmlkpXvec=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
